###
# User Register

POST http://localhost:5000/register
Content-Type: application/json
Accept: application/json

{
  "name": "nama lengkap",
  "username": "username2",
  "password": "password123"
}
###
# User Login

POST http://localhost:5000/login
Content-Type: application/json
Accept: application/json

{
  "username": "username2",
  "password": "password123"
}

###
# Get All User
GET http://localhost:5000/users
Content-Type: application/json
Accept: application/json

###
# Find User by Id

GET http://localhost:5000/users/1
Content-Type: application/json
Accept: application/json
